### ISSUE TITLE
Implement inverse predicates

### ISSUE THREAD

**Issue by yhamoudi** [ProjetPP/PPP-datamodel-Python#37]

**Comment by yhamoudi** [comment]
:grinning:

**Comment by yhamoudi** [comment]
I try to produce `T(M(),R('bla'),R('bli'),M())` and i obtain (into the final normal form):
```
            "inverse-predicate": {
                "type": "missing"
            },
```

**Comment by ProgVal** [comment]
The inverse predicate is the fourth argument

**Comment by yhamoudi** [comment]
Isn't more consistant to put it at the third place?

**Comment by ProgVal** [comment]
no, because it is optional
